In [7]:
# NumPyをインポート
import numpy as np

# AとBの行列を格納する多次元配列
A = np.array([[0,1],[2,3],[4,5]])
B = np.array([[0,1,2,3,],[4,5,6,7]])

# 行列の積の計算をする
np_dot = np.dot(A,B)

# 計算結果を表示する
print(np_dot)

# 行列の要素の最大値を求める
np.max(np_dot)


[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]


47